### PR TITLE
changing to use virtualfs package to stream device

### PR DESCRIPTION
**Pull request by shawn-hurley**
Thank you for contributing to Velero!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

# Please indicate you've done the following:

- [ ] [Accepted the DCO](https://velero.io/docs/v1.5/code-standards/#dco-sign-off). Commits without the DCO will delay acceptance.
- [ ] [Created a changelog file](https://velero.io/docs/v1.5/code-standards/#adding-a-changelog) or added `/kind changelog-not-required` as a comment on this pull request.
- [ ] Updated the corresponding documentation in `site/content/docs/main`.

### CODE REVIEW

**Comment by dzaninovic** [comment]
We now do not have control over the I/O calls so we can't optimize them by doing Direct I/O, Asynchronous I/O and Read ahead buffering

We also can't monitor the I/O performance by timing individual I/O calls so if there is a bottleneck we will not know if the reason for it is slow disk or slow network.

Restore has these additional issues:
- We are now probably writing zeroes instead of skipping them so it will be slower and can also result in increased space usage for cases where device is backed by a sparse file since this will make the file non-sparse.
- No checking if target file is a block device so if /var/lib/kubelet/plugins is not mounted error message from Kopia could be more confusing.

So it all depends on what the expectations are for this feature but as soon as we need any of the above we will need to go back to using individual I/O calls.

**Comment by shawn-hurley** [comment]
I think that you can do the individual i/o calls by creating your own reader and doing it form there, today kopia copies in certain size blocks, I don't have it at hand. 

Although I do agree that, I think building our own reader such that we can do what you said and push back after testing this.

I am going to change the design to:
1. Use the virtualfs.Streaming instead of deviceEntry
2. Continue to use the reader so that we can do the i/o tricks
3. use our own wrapped restore so that we can do the sparse file/zero-byte stuff. 

I think these are reasonable changes, as they don't impact Kopia implementation if it changes. Unless they remove the use of readers and writers which I feel like would be a huge change to stop using the base interfaces that go uses to do these things.

If you agree let me know but that is my plan for tomorrow.

**Comment by dzaninovic** [comment]
We decided to use this for now and add optimizations that require individual I/O calls in separate PRs.

**Comment by dzaninovic** [comment]
This code was causing backup failure so I reverted it.
```
time="2023-08-09T21:31:47Z" level=info msg="DEBUG: calling StreamingFileFromReader()" controller=dataupload dataupload=velero/backup1-cv4mr logSource="pkg/uploader/kopia/block_backup.go:35" parentSnapshot= path="/host_pods/f6955378-4279-4664-a6e0-96af028bc81b/volumeDevices/kubernetes.io~csi/pvc-28a59308-60f6-4534-83aa-612a73cd336c" realSource=block1/pvc-raw
time="2023-08-09T21:31:47Z" level=info msg="Start to snapshot..." controller=dataupload dataupload=velero/backup1-cv4mr logSource="pkg/uploader/kopia/snapshot.go:188" parentSnapshot= path="/host_pods/f6955378-4279-4664-a6e0-96af028bc81b/volumeDevices/kubernetes.io~csi/pvc-28a59308-60f6-4534-83aa-612a73cd336c" realSource=block1/pvc-raw
time="2023-08-09T21:31:47Z" level=info msg="Searching for parent snapshot" controller=dataupload dataupload=velero/backup1-cv4mr logSource="pkg/uploader/kopia/snapshot.go:203" parentSnapshot= path="/host_pods/f6955378-4279-4664-a6e0-96af028bc81b/volumeDevices/kubernetes.io~csi/pvc-28a59308-60f6-4534-83aa-612a73cd336c" realSource=block1/pvc-raw
time="2023-08-09T21:31:47Z" level=error msg="Async fs backup data path failed" dataupload=backup1-cv4mr error="Failed to run kopia backup: Failed to upload the kopia snapshot for si default@default:block1/pvc-raw: unsupported source: default@default:block1/pvc-raw" error.file="/go/pkg/mod/github.com/kopia/kopia@v0.13.0/snapshot/snapshotfs/upload.go:1291" error.function="[github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).Upload](http://github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).Upload)" logSource="pkg/controller/data_upload_controller.go:328"
```

I added this to make sure code from this PR is getting executed:
```
diff --git a/pkg/uploader/kopia/block_backup.go b/pkg/uploader/kopia/block_backup.go
index caa039ba..d537a96c 100644
--- a/pkg/uploader/kopia/block_backup.go
+++ b/pkg/uploader/kopia/block_backup.go
@@ -32,5 +32,6 @@ func getLocalBlockEntry(kopiaEntry fs.Entry, log logrus.FieldLogger) (fs.Entry,
                }
                return nil, errors.Wrapf(err, "Unable to open the source device %s", path)
        }
+       log.Info("DEBUG: calling StreamingFileFromReader()")
        return virtualfs.StreamingFileFromReader(kopiaEntry.Name(), device), nil
 }
```

**Pull request merged**
